Removed 'Good signature' check on the signature: apparently it isn't always displayed. Changed =xx hex conversions: conversion only if the resulting char is printable and if two chars were converted
git-svn-id: https://oosix.icce.rug.nl/svnroot/remailer/trunk@509 dcc949cb-2a1c-0410-b67a-e7e5ca830264

diff --git a/remailer b/remailer
--- a/remailer
+++ b/remailer
@@ -280,14 +280,14 @@ else
 fi
 
 
-    # verify the signature
-
-grep "$GOODSIGNATURE" tmp/${ID}.signature > tmp/${ID}.debug
-if [ "$?" != "0" ]                  # signature not yet verified
-then
-    $0 $H_OPTION tmp/${ID}.decrypted < tmp/${ID}.decrypted
-fi
-[ "$?" == "0" ] || failed signature $? not verifiable
+#     # verify the signature
+# 
+# grep "$GOODSIGNATURE" tmp/${ID}.signature > tmp/${ID}.debug
+# if [ "$?" != "0" ]                  # signature not yet verified
+# then
+#     $0 $H_OPTION tmp/${ID}.decrypted < tmp/${ID}.decrypted
+# fi
+# [ "$?" == "0" ] || failed signature $? not verifiable
 
     # re-encrypt the mail
 if [ "$H_OPTION" != "" ]
